# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
