# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_auto_20170217_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='file_type',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
