# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0003_auto_20170218_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_follow_friend', models.BooleanField(default=False)),
                ('user_follow_friend_time', models.DateTimeField(auto_now_add=True)),
                ('friend_follow_user', models.BooleanField(default=False)),
                ('friend_follow_user_time', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='last_modified_time',
        ),
    ]
